# -*- coding: utf-8 -*-
"""c1p1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YWM6Zyi7gG5Qm1jzku61v5eu5fu98kTx

# Question 1

```
Develop a program to read a four-digit number and find its
a. Sum of digits
b. Reverse
c. Difference between the product of digits at the odd position
and the product of digits at the even position.
```
"""

N = int(input("Enter a 4 digit number: "))
#Extraction of digits
d1 = N%10
d2 =(N//10)%10
d3 = (N//100)%10
d4 = (N//1000)%10

#To get sum of digits

sum = d1+d2+d3+d4
print(sum)

# To Find the reverse
rev = d4 + d3*10 + d2*100 + d1*1000
print(rev)

# To find Difference between the product of digits at the odd position
# and the product of digits at the even position.
diff = (d2*d4) - (d1*d3)
print(diff)