# -*- coding: utf-8 -*-
"""c1p2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18UvLbILINSQrcnohUOP7ZY1xHFqDns3p

Develop a program to read the three sides of two triangles and
calculate the area of both. Define a function to read the three sides
and call it. Also, define a function to calculate the area. Print the total
area enclosed by both triangles and each triangle's contribution (%)
towards it.
"""

def Area(a,b,c):
  s = (a+b+c)/2
  Area_1 = ((s*(s-a)*(s-b)*(s-c))**(1/2))
  return Area_1
def  perc_contrib(Ar,ar1,ar2):
  p1 = (ar1/Ar)*100
  print("Triangle 1 gives ",p1,"% of the total area")
  p2 = (ar2/Ar)*100
  print("Triangle 2 gives ",p2,"% of the total area")

#inputs of triangle 
print("Enter the side lengths of triangle 1")
A1 = int(input("side1 : "))
A2 = int(input("side2 : "))
A3 = int(input("side3 : "))

print("Enter the side lengths of triangle 2")
B1 = int(input("side1 : "))
B2 = int(input("side2 : "))
B3 = int(input("side3 : "))

#Total area

Ar1 = Area(A1,A2,A3) 
Ar2 = Area(B1,B2,B3)



#Percentage contributions

T_area = Ar1 + Ar2
print("Total Area = ",T_area)
perc_contrib(T_area,Ar1,Ar2)